=== jojow/devopslang/Devopsfile-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Devopsfile",
    "description": "JSON schema definition for Devopsfiles",
    "type": "object",
    "properties": {
        "name": {
            "description": "The Devopsfile's name or title",
            "type": "string"
        },
        "version": {
            "description": "The Devopsfile's version",
            "type": "string"
        },
        "author": {
            "description": "The maintainer of the Devopsfile",
            "type": "string"
        },
        "description": {
            "description": "Short description what the Devopsfile does",
            "type": "string"
        },
        "globalconfig": {
            "description": "Global configuration for all operations specified by the Devopsfile",
            "type": "object"
        },
        "hosts": {
            "description": "Hosts on which operations are run",
            "type": "object",
            "patternProperties": {
                "[a-zA-Z0-9-_.]+": {
                    "$ref": "#/definitions/host"
                }
            },
            "additionalProperties": false
        },
        "operations": {
            "description": "Operations to be run",
            "type": "object",
            "properties": {
                "deploy": {
                    "$ref": "#/definitions/operation"
                },
                "undeploy": {
                    "$ref": "#/definitions/operation"
                },
                "expose": {
                    "$ref": "#/definitions/operation"
                },
                "unexpose": {
                    "$ref": "#/definitions/operation"
                }
            },
            "patternProperties": {
                "[a-zA-Z0-9-_.]+": {
                    "$ref": "#/definitions/operation"
                }
            },
            "additionalProperties": false,
            "required": [ "deploy" ]
        }
    },
    "required": [ "name", "version", "author", "description", "operations" ],
    "definitions": {
        "host": {
            "type": "object",
            "properties": {
                "default": {
                    "description": "Indicator whether this is the default host",
                    "type": "boolean"
                },
                "existing": {
                    "description": "Indicator whether the host is existing already",
                    "type": "boolean"
                },
                "access": {
                    "description": "Mechanism to access the host, e.g., 'ssh'",
                    "type": "string"
                }
            }
        },
        "operation": {
            "type": "object",
            "properties": {
                "comment": {
                    "description": "Comment on the operation",
                    "type": "string"
                },
                "config": {
                    "description": "Operation-specific configuration; it gets merged with the gobal configuration",
                    "type": "object"
                },
                "artifacts": {
                    "description": "Artifacts that implement the operation",
                    "type": "object",
                    "patternProperties": {
                        "[a-zA-Z0-9-_.]+": {
                            "$ref": "#/definitions/artifact"
                        }
                    },
                    "additionalProperties": false
                },
                "dependencies": {
                    "description": "List of artifact dependencies",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": { "type": "string" },
                        "minItems": 2,
                        "maxItems": 2,
                        "uniqueItems": true
                    }
                },
                "sequence": {
                    "description": "Sequential execution order of artifacts",
                    "type": "array",
                    "items": { "type": "string" },
                    "minItems": 1
                },
                "postoptest": {
                    "description": "Test to be executed after operation run to confirm success of run",
                    "type": "object",
                    "$ref": "#/definitions/artifact"
                }
            },
            "required": [ "artifacts" ]
        },
        "artifact": {
            "type": "object",
            "properties": {
                "host": {
                    "description": "Name of the host on which artifact is run; if no host is defined for artifact, it runs on default host; if no default host is defined in Devopsfile, the invoker of the Devopsfile or the particular operation may determine where to run the artifact (e.g., on localhost, in a sandbox, etc.)",
                    "type": "string"
                },
                "runner": {
                    "description": "Name of the runner to be used to run the artifact",
                    "type": "string"
                },
                "comment": {
                    "description": "Comment on the artifact",
                    "type": "string"
                },
                "config": {
                    "description": "Artifact-specific configuration; it gets merged with the global and operation-specific configuration",
                    "type": "object"
                },
                "prerun": {
                    "description": "Some JavaScript code to be executed before running the artifact, e.g., to transform configuration parameters",
                    "type": "array",
                    "items": { "type": "string" },
                    "minItems": 1
                },
                "postrun": {
                    "description": "Some JavaScript code to be executed after running the artifact",
                    "type": "array",
                    "items": { "type": "string" },
                    "minItems": 1
                }
            }
        }
    }
}

=== jojow/devopslang/samples/chat-app/Devopsfile_v6.json
{
    "name": "chat-app-ops",
    "version": "...",
    "author": "...",
    "description": "...",

    "operations": {
        "deploy": {
            "artifacts": {
                "node.js": {
                    "runner": "chef-solo-runner",
                    "config": {
                        "files": { "nodejs.tar.gz": "http://s3.amazonaws.com/community-files.opscode.com/cookbook_versions/tarballs/4335/original/nodejs.tar.gz?1376517323" },
                        "runlist": [ "recipe[nodejs::default]" ],
                        "nodejs": {
                            "version": "0.10.26",
                            "check_sha": false
                        }
                    }
                },
                "git": {
                    "runner": "chef-solo-runner",
                    "config": {
                        "files": { "git.tar.gz": "http://s3.amazonaws.com/community-files.opscode.com/cookbook_versions/tarballs/6224/original/git20140318-2456-184qsad.?1395184516" },
                        "runlist": [ "recipe[git::default]" ]
                    }
                },
                "get-app": {
                    "runner": "command-runner",
                    "config": {
                        "command": "git clone https://git-server/chatapp.git && cd chatapp && npm install"
                    }
                },
                "start-app": {
                    "runner": "command-runner",
                    "config": {
                        "command": "export PORT=3000 && node ./chatapp/app.js"
                    }
                },
                "mongodb": {
                    "runner": "chef-solo-runner",
                    "config": {
                        "files": { "mongodb.tar.gz": "http://s3.amazonaws.com/community-files.opscode.com/cookbook_versions/tarballs/6346/original/mongodb.tar.gz?1396423886" },
                        "runlist": [ "recipe[mongodb::default]" ]
                    }
                }
            },
            "dependencies": [
                [ "get-app", "git" ],
                [ "start-app", "get-app" ],
                [ "start-app", "node.js" ],
                [ "start-app", "mongodb" ]
            ],
            "postoptest": {
                "runner": "command-runner",
                "config": {
                    "command": "export RESCODE=$(curl -sL -w \"%{http_code}\\n\" \"http://localhost:3000\" -o /dev/null) && [[ \"$RESCODE\" == \"200\" ]] && true || false"
                }
            }
        }
    }
}

=== jojow/devopslang/samples/chat-app-ops/Opsfile_v1.json
{
    "name": "chat-app-ops",
    "version": "0.1",
    "author": "Johannes <wettinger@iaas.uni-stuttgart.org>",
    "description": "Automated deployment and operations for the chat application",

    "operations": {
        "deploy": {
            "artifacts": {
                "chat-app": {}
            }
        }
    }
}

=== jojow/devopslang/samples/chat-app/Devopsfile_v4.json
{
    "name": "chat-app",
    "version": "...",
    "author": "...",
    "description": "...",

    "operations": {
        "build": {
            "artifacts": {
                "get-app": {
                    "runner": "command-runner",
                    "comment": "git must be installed",
                    "config": {
                        "command": "git clone https://git-server/chatapp.git"
                    }
                },
                "install-deps": {
                    "runner": "command-runner",
                    "comment": "Node.js 0.10 or better must be installed",
                    "config": {
                        "command": "npm install",
                        "cwd": "./chatapp"
                    }
                }
            },
            "dependencies": [
                [ "install-deps", "get-app" ]
            ]
        },
        "start": {
            "artifacts": {
                "chat-app": {
                    "runner": "command-runner",
                    "comment": "Node.js 0.10 or better must be installed",
                    "config": {
                        "command": "node app.js",
                        "cwd": "./chatapp"
                    }
                },
                "mongodb": {
                    "runner": "command-runner",
                    "comment": "MongoDB 2.6 or better must be installed",
                    "config": {
                        "command": "mongod --syslog --maxConns 10"
                    }
                }
            },
            "dependencies": [
                [ "chat-app", "mongodb" ]
            ]
        },
        "deploy": {
            "artifacts": {
                "build": {
                    "runner": "operation-runner",
                    "config": {
                        "operation": "build"
                    }
                },
                "start": {
                    "runner": "operation-runner",
                    "config": {
                        "operation": "start"
                    }
                }
            },
            "dependencies": [
                [ "start", "build" ]
            ]
        }
    }
}

=== jojow/devopslang/samples/chat-app/Devopsfile_v7.json
{
    "name": "chat-app-ops",
    "version": "...",
    "author": "...",
    "description": "...",

    "globalconfig": {
        "chatapp": {
            "port": 3000,
            "https_only": true
        }
    },

    "operations": {
        "deploy": {
            "config": {
                "nodejs": {
                    "version": "0.10.26"
                }
            },
            "artifacts": {
                "node.js": {
                    "runner": "chef-solo-runner",
                    "config": {
                        "files": { "nodejs.tar.gz": "http://s3.amazonaws.com/community-files.opscode.com/cookbook_versions/tarballs/4335/original/nodejs.tar.gz?1376517323" },
                        "runlist": [ "recipe[nodejs::default]" ],
                        "nodejs": {
                            "check_sha": false
                        }
                    }
                },
                "run-app": {
                    "runner": "command-runner",
                    "config": {
                        "files": { "run-app.sh": "git://git-server/chatapp.git/scripts/run-app.sh" },
                        "command": "sh ./run-app.sh"
                    }
                },
                "mongodb": {
                    "runner": "chef-solo-runner",
                    "config": {
                        "files": { "mongodb.tar.gz": "http://s3.amazonaws.com/community-files.opscode.com/cookbook_versions/tarballs/6346/original/mongodb.tar.gz?1396423886" },
                        "runlist": [ "recipe[mongodb::default]" ]
                    }
                }
            },
            "dependencies": [
                [ "run-app", "node.js" ],
                [ "run-app", "mongodb" ]
            ],
            "postoptest": {
                "runner": "command-runner",
                "config": {
                    "command": "export RESCODE=$(curl -sL -w \"%{http_code}\\n\" \"http://localhost:3000\" -o /dev/null) && [[ \"$RESCODE\" == \"200\" ]] && true || false"
                }
            }
        }
    }
}

=== jojow/devopslang/samples/chat-app/Devopsfile_v10.json
{
    "name": "chat-app-ops",
    "version": "...",
    "author": "...",
    "description": "...",

    "globalconfig": {
        "chatapp": {
            "port": 3000,
            "https_only": true
        },
        "aws": {
            "access-key-id": "TBD",
            "secret-access-key": "TBD",
            "vm-props": {
                "app-vm": {
                    "size": "m1.small"
                },
                "db-vm": {
                    "size": "m1.large"
                }
            },
            "sec-groups": {
                "chat": {
                    "members": [ "app-vm", "db-vm" ]
                }
            }
        }
    },

    "hosts": {
        "sandbox": {
            "existing": true,
            "access": "js-sandbox"
        },
        "app-vm": {},
        "db-vm": {}
    },

    "operations": {
        "deploy": {
            "artifacts": {
                "provision-app-vm": {
                    "host": "sandbox",
                    "runner": "js-runner",
                    "config": {
                        "files": { "ec2-provision.js": "http://ops-artifact-store/aws-management/ec2-provision.js" },
                        "include": [ "ec2-provision.js" ]
                    },
                    "prerun": [
                        "// some sandboxed JavaScript code to transform and/or map config parameters...",
                        "config['instance-type'] = globalconfig.aws['vm-props']['app-vm'].size;"
                    ]
                },
                "provision-db-vm": {
                    "host": "sandbox",
                    "runner": "js-runner",
                    "config": {
                        "files": { "ec2-provision.js": "http://ops-artifact-store/aws-management/ec2-provision.js" },
                        "include": [ "ec2-provision.js" ]
                    },
                    "prerun": [
                        "config['instance-type'] = globalconfig.aws['vm-props']['db-vm'].size;"
                    ]
                },
                "deploy-app-core": {
                    "host": "sandbox",
                    "runner": "operation-runner",
                    "config": {
                        "Opsfile": "git://git-server/chatapp.git/core/Devopsfile",
                        "operation": "deploy"
                    }
                },
                "mongodb": {
                    "host": "db-vm",
                    "runner": "chef-solo-runner",
                    "config": {
                        "files": { "mongodb.tar.gz": "http://s3.amazonaws.com/community-files.opscode.com/cookbook_versions/tarballs/6346/original/mongodb.tar.gz?1396423886" },
                        "runlist": [ "recipe[mongodb::default]" ]
                    }
                }
            },
            "dependencies": [
                [ "mongodb", "provision-db-vm" ],
                [ "deploy-app-core", "provision-app-vm" ],
                [ "deploy-app-core", "mongodb" ]
            ],
            "postoptest": {
                "host": "sandbox",
                "runner": "js-runner",
                "config": {
                    "files": { "postdeploytest.js": "git://git-server/chatapp.git/test/post-deployment.js" },
                    "include": [ "postdeploytest.js" ]
                }
            }
        },
        "expose": {
            "artifacts": {
                "update-sec-group": {
                    "host": "sandbox",
                    "runner": "js-runner",
                    "config": {
                        "aws": {
                            "sec-groups": {
                                "chat": {
                                    "inbound": [
                                        { "protocol": "TCP", "port": 80 }
                                    ]
                                }
                            }
                        },
                        "files": { "ec2-update-secgroup.js": "http://ops-artifact-store/aws-management/ec2-update-secgroup.js" },
                        "include": [ "ec2-update-secgroup.js" ]
                    }
                }
            }
        }
    }
}

=== jojow/devopslang/samples/chat-app-ops/Opsfile_v4.json
{
    "name": "chat-app-ops",
    "version": "...",
    "author": "...",
    "description": "...",

    "operations": {
        "deploy": {
            "artifacts": {
                "chat-app": {
                    "runner": "command-runner",
                    "comment": "Node.js 0.10 or better must be installed; git must be installed",
                    "config": {
                        "command": "git clone https://git-server/chatapp.git && cd chatapp && node app.js"
                    }
                },
                "mongodb": {
                    "runner": "command-runner",
                    "comment": "MongoDB 2.6 or better must be installed",
                    "config": {
                        "command": "mongod --syslog --maxConns 10"
                    }
                }
            },
            "dependencies": [
                [ "chat-app", "mongodb" ]
            ]
        }
    }
}

=== jojow/devopslang/samples/chat-app/Devopsfile_v2.json
{
    "name": "chat-app",
    "version": "...",
    "author": "...",
    "description": "...",

    "operations": {
        "build": {
            "artifacts": {
                "install-deps": {
                    "runner": "command-runner",
                    "comment": "Node.js 0.10 or better must be installed",
                    "config": {
                        "command": "npm install"
                    }
                }
            }
        },
        "start": {
            "artifacts": {
                "chat-app": {
                    "runner": "command-runner",
                    "comment": "Node.js 0.10 or better must be installed",
                    "config": {
                        "command": "node app.js"
                    }
                }
            }
        },
        "deploy": {
            "artifacts": {
                "build": {
                    "runner": "operation-runner",
                    "config": {
                        "operation": "build"
                    }
                },
                "start": {
                    "runner": "operation-runner",
                    "config": {
                        "operation": "start"
                    }
                }
            },
            "dependencies": [
                [ "start", "build" ]
            ]
        }
    }
}

=== jojow/devopslang/samples/chat-app/Devopsfile_v5.json
{
    "name": "chat-app",
    "version": "...",
    "author": "...",
    "description": "...",

    "operations": {
        "build": {
            "artifacts": {
                "get-app": {
                    "runner": "command-runner",
                    "comment": "git must be installed",
                    "config": {
                        "command": "git clone https://git-server/chatapp.git"
                    }
                },
                "install-deps": {
                    "runner": "command-runner",
                    "config": {
                        "command": "npm install",
                        "cwd": "./chatapp"
                    }
                }
            },
            "dependencies": [
                [ "install-deps", "get-app" ]
            ]
        },
        "start": {
            "artifacts": {
                "chat-app": {
                    "runner": "command-runner",
                    "config": {
                        "command": "node app.js",
                        "cwd": "./chatapp"
                    }
                },
                "mongodb": {
                    "runner": "command-runner",
                    "config": {
                        "command": "mongod --syslog --maxConns 10"
                    }
                }
            },
            "dependencies": [
                [ "chat-app", "mongodb" ]
            ]
        },
        "deploy": {
            "artifacts": {
                "deploy-nodejs": {
                    "runner": "command-runner",
                    "config": {
                        "command": "sudo add-apt-repository ppa:chris-lea/node.js && sudo apt-get update && sudo apt-get install python-software-properties python g++ make nodejs"
                    }
                },
                "deploy-mongodb": {
                    "runner": "command-runner",
                    "config": {
                        "command": "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10 && echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list && sudo apt-get update && sudo apt-get install mongodb-org"
                    }
                },
                "build": {
                    "runner": "operation-runner",
                    "config": {
                        "operation": "build"
                    }
                },
                "start": {
                    "runner": "operation-runner",
                    "config": {
                        "operation": "start"
                    }
                }
            },
            "sequence": [
                "deploy-nodejs",
                "deploy-mongodb",
                "build",
                "start"
            ]
        }
    }
}
